### ISSUE TITLE
Errore nella protocollazione di email

### ISSUE THREAD

**Issue by riccardogilli** [seedoo/seedoo-core#16]
Buongiorno,
provando a protocollare una email riscontro un errore che mi impedisce di continuare.
Ho installato Seedoo seguendo la procedura due giorni fa, quindi è aggiornato.
Ho visto che c'è un issue simile, #9, ma il codice di errore e la descrizione dell'errore mi sembrano diverse.
Sotto allego il traceback.
Ciao a tutti e grazie,
Riccardo

```Traceback (most recent call last):
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/riccardo/seedoo/OCB/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/home/riccardo/seedoo/OCB/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/riccardo/seedoo/OCB/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/riccardo/seedoo/OCB/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/riccardo/seedoo/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/riccardo/seedoo/seedoo-core/seedoo_protocollo/wizard/create_protocollo_mailpec_wizard.py", line 356, in action_save
    body_pdf_content = base64.b64encode(ConversionUtility.html_to_pdf(wizard.body))
  File "/home/riccardo/seedoo/seedoo-core/seedoo_protocollo/wizard/utility/conversion.py", line 43, in html_to_pdf
    tempfile = ConversionUtility.html_to_pdf_file(body=body, css_file=css_file)
  File "/home/riccardo/seedoo/seedoo-core/seedoo_protocollo/wizard/utility/conversion.py", line 37, in html_to_pdf_file
    extra_args=extra_args)
  File "/home/riccardo/seedoo/venv/local/lib/python2.7/site-packages/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/home/riccardo/seedoo/venv/local/lib/python2.7/site-packages/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "47" during conversion: [WARNING] This document format requires a nonempty <title> element.
  Defaulting to '-' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
wkhtmltopdf not found. Please select a different --pdf-engine or install wkhtmltopdf```

**Comment by othin1** [comment]
con una installazione pulita mi appare lo stesso errore durante la creazione di un protocollo

```
Traceback (most recent call last):
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/home/sservizi/seedoo/OCB/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/sservizi/seedoo/OCB/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/sservizi/seedoo/OCB/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/sservizi/seedoo/seedoo-core/seedoo_protocollo/model/protocollo_permissions.py", line 585, in read
    return super(protocollo_protocollo, self).read(cr, uid, ids, fields, context, load)
  File "/home/sservizi/seedoo/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/sservizi/seedoo/OCB/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/home/sservizi/seedoo/OCB/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/sservizi/seedoo/OCB/openerp/models.py", line 3367, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/sservizi/seedoo/OCB/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/sservizi/seedoo/seedoo-core/seedoo_protocollo/model/protocollo_permissions.py", line 1818, in _elimina_visibility
    not protocollo.doc_imported_ref:
AttributeError: 'protocollo.protocollo' object has no attribute 'doc_imported_ref'
OK
```
