### ISSUE TITLE
Errore server

### ISSUE THREAD

**Issue by forestas** [seedoo/seedoo-core#7]
Salve, ho messo su una macchina virtuale come da guida e l'installazione e andata benissimo. Ho registrato anche alcuni protocolli test e chiuso anche il registro giornaliero e tutto ok. Però quando vado a vedere i documenti registrate si genera questo errore, come si risolve?

Traceback (most recent call last):
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/home/fmura/seedoo/ocb/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/home/fmura/seedoo/ocb/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/fmura/seedoo/ocb/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3370, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/fmura/seedoo/ocb/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/fmura/seedoo/ocb/openerp/osv/fields.py", line 1534, in _related_read
    res[record.id] = value[self.arg[-1]]
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 5679, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/fmura/seedoo/ocb/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/home/fmura/seedoo/ocb/openerp/fields.py", line 928, in determine_value
    record._prefetch_field(self)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3246, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/fmura/seedoo/ocb/openerp/addons/base/ir/ir_attachment.py", line 319, in read
    return super(ir_attachment, self).read(cr, uid, ids, fields_to_read, context=context, load=load)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/ocb/openerp/models.py", line 3370, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/fmura/seedoo/ocb/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/fmura/seedoo/seedoo-core/seedoo_protocollo/model/ir_attachment.py", line 71, in _data_get
    bin_size)
  File "/home/fmura/seedoo/ocb/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/fmura/seedoo/seedoo-core/seedoo_protocollo/model/ir_attachment.py", line 236, in _file_read
    r = os.path.getsize(full_path)
  File "/home/fmura/seedoo/venv/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] File o directory non esistente: '/tmp/protocollazioni/seedoo/cb/cb7f0876b0f7c553da2b6b4d95bbe3a0c500c3d3-270'

**Comment by giuseppearcea** [comment]
Ciao, per favore mi potresti dire se hai risolto ? Anche io ho lo stesso problema, non riesco a vedere i protocolli piu' vecchi di un giorno.

Grazie

**Comment by sardylan** [comment]
L'errore riportato è dovuto al fatto che i protocolli vengono salvati di default nella cartella /tmp.
Al riavvio della macchina il sistema operativo cancella tutto il contenuto della /tmp, per cui si perdono i protocolli salvati.
Come da guida (https://github.com/seedoo/seedoo-core/wiki/Come-Iniziare#configurazione-percorso-salvataggio-dati), occorre configurare il percorso di salvataggio degli attachment in una directory appositamente creata.

Le segnalazioni aperte nella sezione Issues riguardano argomenti tecnici relativi al codice sorgente dell'applicazione, a suggerimenti sull'implementazione delle funzionalità ed alla segnalazione di bug.
Vi invito ad iscrivervi sul forum dedicato, raggiungibile all'indirizzo https://forum.seedoo.it, in cui potete trovare maggior informazioni ed assistenza diretta da parte della community.
